### ISSUE TITLE
How to pass a environment variable to WML

### ISSUE THREAD

**Issue by richdyang** [filebench/filebench#95]
I read the wiki, it said by $(..), but when I run it, it complained. 

I know the document is really outdated. Please help me

**Comment by gamvrosi** [comment]
Hi Richard, can you add a pointer to the entry you read on the Wiki, and also your input script (or part of it) and the output of Filebench when you ran it?

**Comment by richdyang** [comment]
Hi @gamvrosi 
I referred to https://github.com/filebench/filebench/wiki/Workload-model-language#debug

P.S: I am new to I/O, could you explain more about what is iosize, memsize? I am still confused about these terms.

**Comment by richdyang** [comment]
Hi @gamvrosi 

My scenario is to test file write. The file size is 20B ~ 2K, and I need to fill a storage of 2T. The directory depth is 5 at most.

I modified FILEBENCH_NFILESETENTRIES to (1024 * 1024 * 64).

So I set the file number to: 1024*1024*16
I don't prealloc the fileset. I run the filebench, but found the program seems to run at fileset.c fileset_pickreset(..) function. From there, I don't see any output in the log.

**Comment by sectorsize512** [comment]
Hey! We got rid of environmental variables in commit 916b48a434b8f8441a58ca6445ac3e0cfbf03045 for several reasons. One is simplicity and code cleanup. Another is that we want the .f to be self-contained so that people can distribute workloads in a single file, without any external parameters. Therefore, for now you need to regenerate .f file every time you change anything in the workload. Usually people write small shell/perl/python scripts around filebench to automate this task.

HTH,
Vasily

**Comment by sectorsize512** [comment]
I removed the mentioning of environmental variables from the wiki.

**Comment by sectorsize512** [comment]
To test sequential write to a file or files workloads/filemicro_seqwrite.f file is a good start. You would need to remove "prealloc" not to preallocate the file.
