### ISSUE TITLE
How maintain always constant depth and width of the directory structure?

### ISSUE THREAD

**Issue by ashokkumaralluri** [filebench/filebench#98]
Hi Team,

Please help me with filebench params/config that  can always maintain constant depth and width of directory hierarchy.  
Let's say  I want always 100 directory width from top to down at depth of 3 and each directory to have 10 files each at the leaf dirs. what are the params should I set for this?

Thanks,
Ashok

**Comment by sectorsize512** [comment]
Well, the short answer is that there is no way to define exactly such a file system tree in Filebench. The reason is because in your tree directory width is 100 at all levels *except* the bottom one, where the directory width is 10 (10 files per directory). However, Filebench treats all the levels the same and dirwidth parameter defines directory width for all levels (including the bottom one, where the files reside).

The closest you can get to what you want, I think, is the following:

define fileset name=testset,dirwidth=10,entries=1000,dirgamma=0

In this case every level should have 10 directories and the lowest level will have 10 files per directories.

HTH,
Vasily

**Comment by ashokkumaralluri** [comment]
Thanks Vasily. I promise that this is my last question , How does dirgamma=0 affect the directory hierarchy. There is explanation in  https://github.com/filebench/filebench/wiki/Workload%20Model%20Language#attributes , but could not get it much out of it. Before experimenting with it, just trying to understand a bit about it. Probably one example would help me in understanding it better.

Thanks,
Ashok

**Comment by sectorsize512** [comment]
By default Filebench does not fix directory tree  width a fixed directory width at every level. Instead, it uses a gamma distribution. "dirgamma" attribute sets gamma parameter of gamma distribution. If gamma is zero, Filebench does not use gamma distribution and generates the exact number of entries at every level.

HTH,
Vasily

**Comment by ashokkumaralluri** [comment]
Apologies for late reply. "dirgamma" is helpful. Thanks Vasily.

Thanks,
Ashok
